### ISSUE TITLE
Video Resolution and Installation

### ISSUE THREAD

**Issue by genesisgabiola** [theIYD/coursehunt#12]
Is there anyway to select a resolution for the video to download? and is it not better if we can just install the app using npm? or any package manager and access it anywhere in the PC.

**Comment by theIYD** [comment]
To answer your first question, coursehunters have their videos on a standard resolution. You can check out their website. Secondly, the project is a desktop application. You can download it anywhere and have the access to get the videos.

**Comment by genesisgabiola** [comment]
Thank you for your response, I just thought it's the same project from this https://github.com/alekseylovchikov/ch-download . It's my mistake I didn't see that this was made using electron. I tried to install it in in my WSL and I got an error when I tried to start, maybe it's not compatible with WSL? maybe I need to install it just using node in windows?

**Comment by theIYD** [comment]
The windows version mentioned in the release works perfectly fine.

**Comment by genesisgabiola** [comment]
I'm using nvm in WSL which is linux in windows, and it's not working but I'll try again, and if it didn't work I'l try the node in windows.
