### ISSUE TITLE
Pause button not working 

### ISSUE THREAD

**Issue by THEKINGIII** [theIYD/coursehunt#14]
**Description:**
Pause button shall pause the download process to continue downloading process at any time.

**Expected Result:**
Download process stop.

**Actual Result:** 
The downloading process continues directly after clicking on the pause button. Which yields to stop the whole downloading because of network disconnection. And I have to **redownload** all videos again from the beginning because **there is no resuming at all**.

**Comment by THEKINGIII** [comment]
To be more specific this issue happened on company network connection. I uninstalled the app and download it again, currently on my home network, the pause button is working. So I will update the status for this again when I tested that at company network later on.

**Comment by theIYD** [comment]
I guess there must an issue with the connection. 

It works fine.

**Comment by THEKINGIII** [comment]
**So here is a video that describes the issue well** 

https://mega.nz/#!wlhhTCDQ!KXXhUVFRMwM0sNCZiyxqJND2qgbP3UCZnWIFHtufoo4

**Comment by theIYD** [comment]
Please upload the video on Youtube or Google drive

**Comment by makindiilete** [comment]
The pause button is truly not working and it is painful because i want to download a large file of 14gig and i dont have all the data at once. i need to be able to pause. 
![pause](https://user-images.githubusercontent.com/44997832/54980935-625e7100-4fa7-11e9-9c65-85ec69e7938a.png)

**Comment by makindiilete** [comment]
please do help to fix this

**Comment by theIYD** [comment]
I will look into this issue further. A new release is on its way very very soon. :)
