### ISSUE TITLE
Course Hunter Steals Courses

### ISSUE THREAD

**Issue by klamping** [theIYD/coursehunt#16]
Great of you to offer something open-source, but coursehunter steals course content and re-sells it for their own profit. By using them instead of paying for the course from the maker themselves, you're making it harder for the people who devote their time and effort to continue producing worthwhile content.

**Comment by theIYD** [comment]
Hello @klamping 

The application does not in any means support coursehunters in terms of their work. This was developed with the aim of contributing to the open source community by learning how web scraping works and how we can download video links to our computer. 

I, with all my heart support the course creators who put in their time and efforts for the world. 

Thank you.
