### ISSUE TITLE
Not Working | Coursehunter Site Redesigned

### ISSUE THREAD

**Issue by haideritx** [theIYD/coursehunt#20]
Course Hunter site has been redesigned, 
So it is not fetching series episodes. and download is not working.

**Comment by theIYD** [comment]
I haven't been recently working on the app. If you can contribute, you can go ahead and make the required changes and make the app functional. 

I'll be back on this project very soon !

**Comment by Irantwomiles** [comment]
I just submitted a pull request to fix this issue.

**Comment by theIYD** [comment]
This issue was fixed
