### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Benjamin-Daniel** [theIYD/coursehunt#25]
I ran npm install then npm start. When i inputed the url in the input box and press get videos, Nothing happens.
![Screenshot from 2019-07-03 14-18-50](https://user-images.githubusercontent.com/19100745/60594748-8814c680-9d9d-11e9-920b-1e64fdb1d19f.png)

**Comment by theIYD** [comment]
Can you try downloading the `release` version from the **Releases** tab ?

**Comment by Benjamin-Daniel** [comment]
I just did. Doesn't show any thing after clicking get Videos.
![Screenshot from 2019-07-04 19-17-39](https://user-images.githubusercontent.com/19100745/60683600-7a8c3900-9e90-11e9-958d-b6e1587af8d2.png)

**Comment by jofwar** [comment]
Same issue

**Comment by the777misa** [comment]
Same issue

**Comment by zjoin** [comment]
Hey! not working

**Comment by theIYD** [comment]
I am debugging on what went wrong in the latest release.

**Comment by Benjamin-Daniel** [comment]
Okay thanks, we are waiting for you.

**Comment by saostad** [comment]
I submitted a pull request with required fixes.

**Comment by theIYD** [comment]
@saostad Thank you for the pull request which was required with proper changes. ***Release 0.0.7*** working

**Comment by Benjamin-Daniel** [comment]
Thanks
