### ISSUE TITLE
Doesn't works on ubuntu 18.04

### ISSUE THREAD

**Issue by kumaranvpl** [theIYD/coursehunt#9]
It fetches the lessons correctly.
But after selecting the folder to download, it throws an error in console.

**Comment by theIYD** [comment]
Can you post the console error ?

**Comment by kumaranvpl** [comment]
@theIYD I tried to download this course https://coursehunters.net/course/yazyk-programmirovaniya-rust. Is this because this course is protected or something like that?

**Comment by theIYD** [comment]
Please read the instructions on the course page. It is clearly given that the course will be available after a month. 

Closing this issue....

**Comment by kumaranvpl** [comment]
@theIYD I don't know what language is this. Even google translate doesn't translates this page. DO you have any suggestions?

**Comment by kumaranvpl** [comment]
@theIYD Please consider adding a feature to let users know that the course is a paid one and cannot be downloaded. Let me create an issue for this separately to track this feature.

**Comment by theIYD** [comment]
@kumaranvpl I am on it. Thanks for the suggestion.

**Comment by theIYD** [comment]
@kumaranvpl The language is russian. It translates fine on Google Chrome. Although, i am adding a feature of showing information which says if the course is protected or not ...

**Comment by kumaranvpl** [comment]
@theIYD I guess it is some chrome setting configuration problem on my side. I fixed it. 
And sometimes clicking the download button prompts me to select target folder twice. And proceeds to download twice simultaneously. I am pretty sure this is a simple bug which you can fix easily. But it prompt me to think of another feature. You could download videos simultaneously. JS is asynchronous. So this is totally possible. Also to prevent bandwidth clogging, limit the simultaneous downloads to 3 or 5.

**Comment by theIYD** [comment]
@kumaranvpl In case of asynchronous downloads, if the internet goes off, the downloaded files will get corrupted and have to be downloaded again. Also, the application was built considering users have low internet speeds (like me), so downloading multiple files will result to a server error due to slow speeds getting widely distributed to files.

**Comment by kumaranvpl** [comment]
@theIYD I am pretty sure downloading 2 files simultaneously is not going to slow your download speed significantly.

To overcome the failed downloads synario

1. While starting download of course, check folder already exists
2. If already exists then check how many files are downloaded already
3. Check downloaded files size is same as the size served by server
4. Redownload corrupted files and download remaining files(simultaneously if possible)

**Comment by theIYD** [comment]
@kumaranvpl I will think upon it.
